Camille.configure do |config|
  # Contents to be placed at the beginning of the output TypeScript file.
  config.ts_header = <<~EOF
    // DO NOT EDIT! This file is automatically generated.
    import request from './request'
  EOF

  # Enable type checking for controller parameters.
  # When enabled, params will be validated against the schema and automatically
  # converted from camelCase to snake_case.
  config.check_params = true
end